# -*- coding: utf-8 -*-
"""Data_Loading&Data_Cleaning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oh-tKuXCjQDWP5cPkcLS7whEiEOorR6N

**Data Loading**
"""

# loading product review data
import pandas as pd
pr_data = pd.read_csv('/content/Product_reviews_description_data.csv')
pr_data.describe()

pr_data.head()

"""**Data Cleansing**"""

# Data Cleansing
pr_data.isnull().sum()

pr_data.fillna('', inplace=True)
pr_data.isnull().sum()