# -*- coding: utf-8 -*-
"""Embedding.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d8RZEtABKRLdmS_B8OP8reXMbrgfyH6O

**Embedding the reviews:**
"""

# Embedding
import numpy as np
from sentence_transformers import SentenceTransformer
model = SentenceTransformer('jinaai/jina-embedding-s-en-v1')
def generate_embeddings(input_df):
    all_embeddings = []

    for t in input_df.Cleaned_content:
        review_embeddings = []
        all_embeddings.append(np.array(model.encode(t)))

    input_df["embeddings"] = all_embeddings
    return input_df

enhanced_dataframe = generate_embeddings(filtered_df)

enhanced_dataframe.head()