# -*- coding: utf-8 -*-
"""Libraries_keys.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KQZu_lePER4Yg9HBFiSgArCNdJIxIrE0
"""

!pip install  numpy
!pip install faiss-cpu
!pip install sentence_transformers
!pip install langchain
!pip install llama-index
!pip install llama-index-llms-openai
!pip install llama-index-embeddings-jinaai
!pip install llama-index-llms-huggingface
!pip install "huggingface_hub[inference]"

# required keys
Japi_key = "jina_003279306e15431eb5d5d8f9d63f0621Xfl_KnauOYejyQ4WwVMzdpAja5RK"
huggingface_api_key: str = "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"