# -*- coding: utf-8 -*-
"""Reranking.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wUausddacvxp0gpm0kTKELRTYvxMqCcW

**Re-Ranking:**
"""

# reranking  and getting top 5 reviews
from sentence_transformers import CrossEncoder

jina_reranking_model = CrossEncoder("jinaai/jina-reranker-v1-tiny-en", trust_remote_code=True)

results = jina_reranking_model.rank(query, search_results, return_documents=True, top_k=5)

all_reviews = [item['text'] for item in results]
print(np.array(all_reviews))