# -*- coding: utf-8 -*-
"""Review_Retrieval.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ghzRsqhZC0tJGetml28jBFaOCQxN_M7l

**Review_Retrieval:**
"""

# Retriving top 20 results
def find_similar_texts(query, n=21):
    query_embedding = model.encode(query)
    query_embedding = np.ascontiguousarray(
        np.array(query_embedding, dtype="float32").reshape(1, -1)
    )
    faiss.normalize_L2(query_embedding)
    similarities, indices = index.search(query_embedding, n)
    results = []
    num_valid_indices = min(n, len(enhanced_dataframe))
    for i in range(num_valid_indices):
        similarity = similarities[0][i]
        index_id = indices[0][i]
        while index_id < 0 or index_id >= len(enhanced_dataframe):
            i += 1
            if i >= num_valid_indices:
                break
            index_id = indices[0][i]
        if index_id < 0 or index_id >= len(enhanced_dataframe):
            continue
        result_text = enhanced_dataframe.loc[index_id, "Cleaned_content"]
        results.append(result_text)
    return results[:n]

query = "platform"
search_results = find_similar_texts(query)
print(np.array(search_results))