# -*- coding: utf-8 -*-
"""Vector_Database_Creation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ir5dEftAffbsWJsAWubTyyU4QM0bxblE

**Vector Database Creation:**
"""

# vector database creation
import faiss
import numpy as np

if 'embeddings' not in enhanced_dataframe.columns:
    print("Error: 'embeddings' column not found in DataFrame")
else:
    dim = len(enhanced_dataframe['embeddings'].iloc[0])
    index = faiss.IndexFlatIP(dim)
    embeddings_array = np.vstack(enhanced_dataframe['embeddings'])
    faiss.normalize_L2(embeddings_array)
    index.add(embeddings_array)

expected_indexes = range(len(filtered_df))
# Find missing indexes
missing_indexes = [index for index in expected_indexes if index not in filtered_df.index or index == -1]